### ISSUE TITLE
Fehler beim Installieren/Shopware5.1.2

### ISSUE THREAD

**Issue by mbrandau** [dnoegel/DsnFrontendBlocks#1]
Uploaded zip archive contains no plugin namespace directory: Bootstrap.php

Dieser Fehler wird angezeigt wenn man versucht das Plugin über den Plugin Manager hochzuladen und zu installieren.

**Comment by bcremer** [comment]
Wenn das Plugin über den Plugin Manager installiert werden soll, muss der Inhalt noch in einen Ordner `Frontend` verschoben werden bevor es gezipped wird. Die Verzeichnisstruktur kannst du dir z.b in diesem Beispielplugin abgucken: https://developers.shopware.com/exampleplugins/SwagMd5Reversed.zip

Alternativ kannst du das Plugin auch direkt per git in das richtige Verzeichnis auschecken:
`git clone https://github.com/dnoegel/DsnFrontendBlocks.git /var/www/dein.shop.de/engine/Shopware/Plugins/Local/Frontend/DsnFrontendBlocks`

**Comment by mbrandau** [comment]
Danke funktioniert.
